security:
    encoders:
        Acme\KLBundle\Entity\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ROLE_ADMIN:  
            entity: { class: AcmeKLBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/staff/*
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check                
            logout:
                path:   logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/staff/, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext