security:
    encoders:
        Acme\KLBundle\Entity\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        default_provider:
#            memory:
#                users:
#                    ryan: { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
        ROLE_ADMIN:  
            entity: { class: AcmeKLBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/template
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check                
            logout:
                path:   logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/template, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext