<?php

namespace Proxies\__CG__\Acme\KLBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Thontincanhan extends \Acme\KLBundle\Entity\Thontincanhan implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setHoten($hoten)
    {
        $this->__load();
        return parent::setHoten($hoten);
    }

    public function getHoten()
    {
        $this->__load();
        return parent::getHoten();
    }

    public function setQuequan($quequan)
    {
        $this->__load();
        return parent::setQuequan($quequan);
    }

    public function getQuequan()
    {
        $this->__load();
        return parent::getQuequan();
    }

    public function setCmtnd($cmtnd)
    {
        $this->__load();
        return parent::setCmtnd($cmtnd);
    }

    public function getCmtnd()
    {
        $this->__load();
        return parent::getCmtnd();
    }

    public function setSdt($sdt)
    {
        $this->__load();
        return parent::setSdt($sdt);
    }

    public function getSdt()
    {
        $this->__load();
        return parent::getSdt();
    }

    public function setNgaysinh($ngaysinh)
    {
        $this->__load();
        return parent::setNgaysinh($ngaysinh);
    }

    public function getNgaysinh()
    {
        $this->__load();
        return parent::getNgaysinh();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'hoten', 'quequan', 'cmtnd', 'sdt', 'ngaysinh', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}