<?php

namespace Proxies\__CG__\Acme\KLBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Tthc extends \Acme\KLBundle\Entity\Tthc implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNametthc($nametthc)
    {
        $this->__load();
        return parent::setNametthc($nametthc);
    }

    public function getNametthc()
    {
        $this->__load();
        return parent::getNametthc();
    }

    public function setNoidungthuchien($noidungthuchien)
    {
        $this->__load();
        return parent::setNoidungthuchien($noidungthuchien);
    }

    public function getNoidungthuchien()
    {
        $this->__load();
        return parent::getNoidungthuchien();
    }

    public function setGiaytohoso($giaytohoso)
    {
        $this->__load();
        return parent::setGiaytohoso($giaytohoso);
    }

    public function getGiaytohoso()
    {
        $this->__load();
        return parent::getGiaytohoso();
    }

    public function setThoigiangiaiquyet($thoigiangiaiquyet)
    {
        $this->__load();
        return parent::setThoigiangiaiquyet($thoigiangiaiquyet);
    }

    public function getThoigiangiaiquyet()
    {
        $this->__load();
        return parent::getThoigiangiaiquyet();
    }

    public function setPhanquyen($phanquyen)
    {
        $this->__load();
        return parent::setPhanquyen($phanquyen);
    }

    public function getPhanquyen()
    {
        $this->__load();
        return parent::getPhanquyen();
    }

    public function setIshide($ishide)
    {
        $this->__load();
        return parent::setIshide($ishide);
    }

    public function getIshide()
    {
        $this->__load();
        return parent::getIshide();
    }

    public function getIdtthc()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idtthc"];
        }
        $this->__load();
        return parent::getIdtthc();
    }

    public function setIdvanbanlienquan(\Acme\KLBundle\Entity\Vanbanlienquan $idvanbanlienquan = NULL)
    {
        $this->__load();
        return parent::setIdvanbanlienquan($idvanbanlienquan);
    }

    public function getIdvanbanlienquan()
    {
        $this->__load();
        return parent::getIdvanbanlienquan();
    }

    public function setIddonvithuly(\Acme\KLBundle\Entity\Donvithuly $iddonvithuly = NULL)
    {
        $this->__load();
        return parent::setIddonvithuly($iddonvithuly);
    }

    public function getIddonvithuly()
    {
        $this->__load();
        return parent::getIddonvithuly();
    }

    public function setIddinhkem(\Acme\KLBundle\Entity\Dinhkemtthc $iddinhkem = NULL)
    {
        $this->__load();
        return parent::setIddinhkem($iddinhkem);
    }

    public function getIddinhkem()
    {
        $this->__load();
        return parent::getIddinhkem();
    }

    public function setIdlinhvuc(\Acme\KLBundle\Entity\Linhvuc $idlinhvuc = NULL)
    {
        $this->__load();
        return parent::setIdlinhvuc($idlinhvuc);
    }

    public function getIdlinhvuc()
    {
        $this->__load();
        return parent::getIdlinhvuc();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nametthc', 'noidungthuchien', 'giaytohoso', 'thoigiangiaiquyet', 'phanquyen', 'ishide', 'idtthc', 'idvanbanlienquan', 'iddonvithuly', 'iddinhkem', 'idlinhvuc');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}